const defaultState = {
  catalogList: [
    {
      id: 1,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/Iphone15.webp"),
      name: "Телефоны и гаджеты",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/samsung.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/xiaomi.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/apple.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/philips.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/sony.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/hiper.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Смартфоны",
          img: require("../Header-catalog-btn/images/Category-list/Iphone.webp"),
          menu: [
            "Apple",
            "Samsung",
            "Xiaomi",
            "TECNO",
            "Infinix",
            "Honor",
            "POCO",
            "Realme",
            "Все смартфоны",
          ],
        },
        {
          id: 2,
          name: "Аксессуары для гаджетов",
          img: require("../Header-catalog-btn/images/Category-list/charger.webp"),
          menu: [
            "Аксессуары для телефонов",
            "Аксессуары для планшетов",
            "Аксессуары для смарт-часов",
            "Аксессуары для наушников",
            "Аксессуары для фото и видеокамер",
            "Зарядные устройства и кабели",
            "Карты памяти",
            "Кольцевые лампы",
          ],
        },
        {
          id: 3,
          name: "Смарт-часы и фитнес-браслеты",
          img: require("../Header-catalog-btn/images/Category-list/smart-watch.webp"),
          menu: [
            "Apple",
            "Samsung",
            "Xiaomi",
            "Huawei",
            "Amazfit",
            "Garmin",
            "Смарт-часы",
            "Детские умные часы",
            "Фитнес браслеты",
            "Все смарт-часы и фитнес-браслеты",
          ],
        },
        {
          id: 4,
          name: "Планшеты",
          img: require("../Header-catalog-btn/images/Category-list/tablet.webp"),
          menu: [
            "Apple",
            "Samsung",
            "Xiaomi",
            "Huawei",
            "Lenovo",
            "Бюджетные",
            "Все планшеты",
          ],
        },
        {
          id: 5,
          name: "Наушники",
          img: require("../Header-catalog-btn/images/Category-list/airpods.webp"),
          menu: ["TWS", "Беспроводные", "Проводные", "Накладные"],
        },
        {
          id: 6,
          name: "Кнопочные телефоны",
          img: require("../Header-catalog-btn/images/Category-list/push-button-telephone.jpg"),
          menu: [
            "Nokia",
            "F+",
            "BQ",
            "Philips",
            "teXet",
            "Все кнопочные телефоны",
          ],
        },
        {
          id: 7,
          name: "Фотоаппараты",
          img: require("../Header-catalog-btn/images/Category-list/photo.webp"),
          menu: false,
        },
        {
          id: 8,
          name: "Электронные книги",
          img: require("../Header-catalog-btn/images/Category-list/E-books.webp"),
          menu: false,
        },
        {
          id: 9,
          name: "Видеокамеры",
          img: require("../Header-catalog-btn/images/Category-list/camera.webp"),
          menu: false,
        },
        {
          id: 10,
          name: "Bluetooth-гарнитуры",
          img: require("../Header-catalog-btn/images/Category-list/bluetooth.webp"),
          menu: false,
        },
        {
          id: 11,
          name: "Смарт-очки",
          img: require("../Header-catalog-btn/images/Category-list/glasses.webp"),
          menu: false,
        },
      ],
    },
    {
      id: 2,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/notebook.png"),
      name: "Компьютерная техника",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/apple.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/acer.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/samsung.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/xiaomi.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/LG.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/philips.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Комплектующие",
          img: require("../Header-catalog-btn/images/Category-list/accessories.webp"),
          menu: [
            "Процессоры",
            "Материнские платы",
            "Оперативная память",
            "Видеокарты",
            "Накопители НDD",
            "Накопители SSD",
            "Корпуса",
            "Кулеры и системы охлаждения",
            "Блоки питания",
            "Вентиляторы для корпуса",
            "Звуковые карты",
            "Приводы",
            "Термопаста",
            "Контроллеры",
            "Аксессуары для систем охлаждения и компоненты для СВО",
          ],
        },
        {
          id: 2,
          name: "Ноутбуки",
          img: require("../Header-catalog-btn/images/Category-list/laptop.webp"),
          menu: [
            "Все ноутбуки",
            "Аррlе МасЬоок",
            "Игровые ноутбуки",
            "Ноутбуки 17",
            "Ноутбуки 15",
            "Ноутбуки 13",
            "Сумки для ноутбуков",
            "Зарядные устройства и блоки питания",
            "Подставки для ноутбуков",
          ],
        },
        {
          id: 3,
          name: "Периферийные устройства",
          img: require("../Header-catalog-btn/images/Category-list/peripherals.webp"),
          menu: [
            "Клавиатуры",
            "Мыши",
            "Коврики для мышей",
            "Компьютерные наушники",
            "Микрофоны",
            "Веб-камеры",
            "USВ хабы",
            "Аксессуары для наушников и гарнитур",
            "Комплекты клавиатур и мышей",
            "Аксессуары для ноутбуков",
            "Кабели и переходники",
            "Графические планшеты",
          ],
        },
        {
          id: 4,
          name: "Компьютеры 05.ru",
          img: require("../Header-catalog-btn/images/Category-list/PC.webp"),
          menu: ["Игровые", "Офисные"],
        },
        {
          id: 5,
          name: "Моноблоки",
          img: require("../Header-catalog-btn/images/Category-list/monoblocks.webp"),
          menu: ["Неттопы", "Моноблоки iMac"],
        },
        {
          id: 6,
          name: "Мониторы",
          img: require("../Header-catalog-btn/images/Category-list/monitors.webp"),
          menu: [
            "Мониторы игровые",
            "Мониторы 2К",
            "Мониторы 4К",
            "Мониторы изогнутые",
            "Все мониторы",
          ],
        },
        {
          id: 7,
          name: "Устройства хранения данных",
          img: require("../Header-catalog-btn/images/Category-list/storage-devices.webp"),
          menu: [
            "USВ Flash drive",
            "Внешние НОР накопители",
            "Внешние 550 накопители",
            "Внешние приводы",
            "СD, DVS диски для записи",
            "Картридеры",
            "Аксессуары для винчестеров",
          ],
        },
        {
          id: 8,
          name: "Проекционное оборудование",
          img: require("../Header-catalog-btn/images/Category-list/projection-equipment.webp"),
          menu: [
            "Проекторы",
            "Кронштейны для проекторов",
            "Экраны для проекторов",
            "Презентеры",
          ],
        },
      ],
    },
    {
      id: 3,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/printer.webp"),
      name: "Офисная техника и сети",
      brand: false,
      lists: [
        {
          id: 1,
          name: "Офисная техника",
          img: require("../Header-catalog-btn/images/Category-list/office-equipment.webp"),
          menu: [
            "Принтеры и МФУ",
            "Сканеры",
            "Принтеры этикеток",
            "Уничтожители бумаги",
            "Ламинаторы",
            "Сканеры штрих-кода",
            "Счетчики банкнот",
          ],
        },
        {
          id: 2,
          name: "Сетевое оборудование",
          img: require("../Header-catalog-btn/images/Category-list/network-equipment.jpg"),
          menu: [
            "Wi-Fi роутеры, точки доступа",
            "Wi-Fi адаптеры",
            "bluetooth адаптеры",
            "Проводные сети",
            "VoIP-о6орудование",
            "Прочее",
          ],
        },
        {
          id: 3,
          name: "Расходные материалы",
          img: require("../Header-catalog-btn/images/Category-list/consumables.webp"),
          menu: [
            "Картриджи",
            "Тонеры, чернила",
            "Бумага",
            "Батарейки и аккумуляторы",
            "Пакеты для ламинирования",
            "Средства ухода за техникой",
            "Расходные материалы для ЗD печати",
          ],
        },
        {
          id: 4,
          name: "Программное обеспечение",
          img: require("../Header-catalog-btn/images/Category-list/software.jpg"),
          menu: ["Антивирусы"],
        },
        {
          id: 5,
          name: "Источники бесперебойного питания",
          img: require("../Header-catalog-btn/images/Category-list/uninterruptible-power-supplies.webp"),
          menu: ["Интерактивные", "Резервные"],
        },
        {
          id: 6,
          name: "Видеонаблюдение",
          img: require("../Header-catalog-btn/images/Category-list/video-surveillance.webp"),
          menu: ["Камеры видеонаблюдения", "Акссесуары для видеонаблюдения"],
        },
        {
          id: 7,
          name: "Сетевые фильтры",
          img: require("../Header-catalog-btn/images/Category-list/network-filters.webp"),
          menu: ["Сетевые удленители", "Сетевые разветвители"],
        },
        {
          id: 8,
          name: "Стабилизаторы",
          img: require("../Header-catalog-btn/images/Category-list/stabilizers.webp"),
          menu: false,
        },
      ],
    },
    {
      id: 4,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/tv.webp"),
      name: "Телевизоры и аксессуары",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/samsung.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/LG.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/philips.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/xiaomi.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/sony.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Телевизоры",
          img: require("../Header-catalog-btn/images/Category-list/TV.webp"),
          menu: [
            "4К UHD-телевизоры",
            "Смарт-телевизоры",
            "QLЕD-телевизоры",
            "Все телевизоры",
          ],
        },
        {
          id: 2,
          name: "Акссесуары для ТВ",
          img: require("../Header-catalog-btn/images/Category-list/TV-accessories.webp"),
          menu: [
            "Медиаплееры",
            "Тюнеры",
            "Антенны",
            "Подставки",
            "Кронштейны",
            "Пульты",
            "Прочее",
          ],
        },
      ],
    },
    {
      id: 5,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/audio-equipment.jpg"),
      name: "Аудиотехника",
      brand: false,
      lists: [
        {
          id: 1,
          name: "Портативное аудио",
          img: require("../Header-catalog-btn/images/Category-list/portable-audio.webp"),
          menu: ["Умные колонки", "Портативные колонки", "Колонки"],
        },
        {
          id: 2,
          name: "Домашнее аудио",
          img: require("../Header-catalog-btn/images/Category-list/home-audio.webp"),
          menu: ["Саундбары", "Музыкальные центры"],
        },
        {
          id: 3,
          name: "Радиоприемники и радиобудильники",
          img: require("../Header-catalog-btn/images/Category-list/radios.webp"),
          menu: false,
        },
      ],
    },
    {
      id: 6,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/ps-5.jpg"),
      name: "Игровые приставки и видеоигры",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/sony.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Игровые приставки",
          img: require("../Header-catalog-btn/images/Category-list/game-consoles.webp"),
          menu: ["РlауStation", "ХЬох", "Nintendo", "Портативные"],
        },
        {
          id: 2,
          name: "Игровые приставки",
          img: require("../Header-catalog-btn/images/Category-list/video-games.jpg"),
          menu: [
            "Игры для РS",
            "Игры для ХЬох",
            "Игры на NS",
            "Игры для двоих",
            "Игры для четверых",
          ],
        },
        {
          id: 3,
          name: "Акссесуары для игровых приставок",
          img: require("../Header-catalog-btn/images/Category-list/accessories-for-console.webp"),
          menu: [
            "Джойстики, геймпады",
            "Рули, контроллеры",
            "Игровые наушники",
            "Прочее",
          ],
        },
        {
          id: 4,
          name: "Устройства виртуальной реальности",
          img: require("../Header-catalog-btn/images/Category-list/virtual-reality-devices.webp"),
          menu: false,
        },
      ],
    },
    {
      id: 7,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/conditioner.webp"),
      name: "Климатическая техника",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/xiaomi.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/electrolux.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/dyson.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/philips.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Кондиционеры",
          img: require("../Header-catalog-btn/images/Category-list/air-conditioners.webp"),
          menu: [
            "Все кондиционеры",
            "Настенные сплит-системы",
            "Мобильные кондиционеры",
          ],
        },
        {
          id: 2,
          name: "Вентеляторы",
          img: require("../Header-catalog-btn/images/Category-list/fans.webp"),
          menu: ["Напольные вентеляторы", "Настольные вентеляторы"],
        },
        {
          id: 3,
          name: "Увлажнители и очистители воздуха",
          img: require("../Header-catalog-btn/images/Category-list/humidifiers.webp"),
          menu: ["Воздухоочистители", "Увлажнители", "Очиститель/увлажнитель"],
        },
        {
          id: 4,
          name: "Обогреватели",
          img: require("../Header-catalog-btn/images/Category-list/heaters.jpg"),
          menu: ["Тепловентеляторы", "Маслянные радиаторы", "Конвекторы"],
        },
        {
          id: 5,
          name: "Домашние метеостанции",
          img: require("../Header-catalog-btn/images/Category-list/home-weather-stations.webp"),
          menu: false,
        },
        {
          id: 6,
          name: "Аксессуары для климатического оборудования",
          img: require("../Header-catalog-btn/images/Category-list/accessories-for-climate.webp"),
          menu: [
            "Модули управления для климатического оборудования",
            "Прочие аксессуары дляклиматического оборудования",
          ],
        },
      ],
    },
    {
      id: 8,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/washing-machine.webp"),
      name: "Бытовая техника",
      brand: false,
      lists: [
        {
          id: 1,
          name: "Крупная бытовая техника",
          img: require("../Header-catalog-btn/images/Category-list/large-household-appliances.jpg"),
          menu: [
            "Стиральные машины",
            "Холодильники",
            "Морозильники",
            "Сушильные машины",
            "Посудомоечные машины",
            "Кулеры для воды",
            "Плиты газовые и электрические",
            "Аксессуары для бытовой техники",
          ],
        },
        {
          id: 2,
          name: "Техника для дома",
          img: require("../Header-catalog-btn/images/Category-list/home-appliances.webp"),
          menu: [
            "Пылесосы",
            "Вертикальные пылесосы",
            "Роботы-пылесосы",
            "Утюги",
            "Отпариватели",
            "Парогенераторы",
            "Пароочистители",
            "Минимойки",
            "Электрические стеклоочистители",
            "Аксессуары",
          ],
        },
        {
          id: 3,
          name: "Техника для кухни",
          img: require("../Header-catalog-btn/images/Category-list/kitchen-appliances.webp"),
          menu: [
            "Чайники электрические",
            "Блендеры",
            "Миксеры",
            "Микроволновые печи",
            "Мясорубки",
            "Тостеры",
            "Соковыжималки",
            "Смесители",
            "Кухонные комбайны, измельчители",
            "Мойки",
            "Кухонные весы",
            "Прочая техника для кухни",
            "Мини-печи",
            "Пароварки",
            "Термопоты",
            "Мульти варки",
            "Настольные плиты",
            "Сэндвичиицы и вафельницы",
            "Хлебопечки",
            "Аэрогрили",
            "Фритюрницы",
            "Сушилки для овощей и фруктов",
            "Электрогрили",
            "Лапшерезки",
            "Аксессуары для мелкой кухонной техники",
          ],
        },
        {
          id: 4,
          name: "Встраиваемая техника",
          img: require("../Header-catalog-btn/images/Category-list/built-in-technology.webp"),
          menu: [
            "Вытяжки",
            "Духовые шкафы",
            "Варочные панели",
            "Измельчители пищевых отходов",
            "Встраиваемые стиральные машины",
            "Встраиваемые холодильники",
            "Встраиваемые посудомоечные машины",
            "Встраиваемые микроволновые печи",
            "Встраиваемые морозильники",
          ],
        },
        {
          id: 5,
          name: "Приготовление кофе и чая",
          img: require("../Header-catalog-btn/images/Category-list/making-coffee-and-tea.webp"),
          menu: [
            "Кофемашины",
            "Кофеварки",
            "Кофемолки",
            "Турки и гейзеры для кофе",
            "Кофе",
            "Молоко",
            "Сиропы",
            "Чай",
            "Аксессуары для приготовления кофе и чая",
          ],
        },
        {
          id: 6,
          name: "Фильтры для воды",
          img: require("../Header-catalog-btn/images/Category-list/water-filters.webp"),
          menu: [
            "Фильтры и умягчители для воды",
            "Картриджи и сменные элементы для бытовых водоочистителей",
          ],
        },
      ],
    },
    {
      id: 9,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/hair-dryer.webp"),
      name: "Красота, здоровье",
      name: "Климатическая техника",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/dyson.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/philips.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/xiaomi.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Приборы для укладки",
          img: require("../Header-catalog-btn/images/Category-list/styling-devices.jpg"),
          menu: ["Плойки", "Выпрямители", "Мультистайлеры", "Гофре"],
        },
        {
          id: 2,
          name: "Сушка волос",
          img: require("../Header-catalog-btn/images/Category-list/drying-hair.webp"),
          menu: [
            "Фены",
            "Акссесуары для фенов",
            "Фен-щетки",
            "Компактные фены",
          ],
        },
        {
          id: 3,
          name: "Стрижки и бритье",
          img: require("../Header-catalog-btn/images/Category-list/haircut-and-shaving.webp"),
          menu: ["Триммеры", "Мужские электробритвы", "Машинки для стрижки"],
        },
        {
          id: 4,
          name: "Напольные весы",
          img: require("../Header-catalog-btn/images/Category-list/bathroom-scales.webp"),
          menu: false,
        },
        {
          id: 5,
          name: "Медицинские приборы",
          img: require("../Header-catalog-btn/images/Category-list/medical-devices.webp"),
          menu: ["Тонометры", "Ингаляторы", "Термометры"],
        },
        {
          id: 6,
          name: "Эпиляторы",
          img: require("../Header-catalog-btn/images/Category-list/epilators.webp"),
          menu: false,
        },
        {
          id: 7,
          name: "Массажеры",
          img: require("../Header-catalog-btn/images/Category-list/massagers.webp"),
          menu: false,
        },
        {
          id: 8,
          name: "Гигиена полости рта",
          img: require("../Header-catalog-btn/images/Category-list/oral-hygiene.webp"),
          menu: [
            "Электрические зубные щетки",
            "Аксессуары для зубных щеток и ирригаторов",
            "Жидкости для ирригатора",
            "Ирригаторы",
          ],
        },
        {
          id: 9,
          name: "Зеркала",
          img: require("../Header-catalog-btn/images/Category-list/mirrors.webp"),
          menu: false,
        },
        {
          id: 10,
          name: "Очки для зрения",
          img: require("../Header-catalog-btn/images/Category-list/glasses-for-vision.webp"),
          menu: false,
        },
        {
          id: 11,
          name: "Щетки для волос",
          img: require("../Header-catalog-btn/images/Category-list/hair-brushes.webp"),
          menu: false,
        },
      ],
    },
    {
      id: 10,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/merch.webp"),
      name: "Мерч «Это 05»",
      brand: false,
      lists: [
        {
          id: 1,
          name: "Падарочные сертификаты",
          img: require("../Header-catalog-btn/images/Category-list/gift-certificates.webp"),
          menu: false,
        },
        {
          id: 2,
          name: "Шопперы",
          img: require("../Header-catalog-btn/images/Category-list/shoppers.webp"),
          menu: false,
        },
        {
          id: 3,
          name: "Открытки",
          img: require("../Header-catalog-btn/images/Category-list/postcards.webp"),
          menu: false,
        },
        {
          id: 4,
          name: "Браслеты",
          img: require("../Header-catalog-btn/images/Category-list/bracelets.webp"),
          menu: false,
        },
        {
          id: 5,
          name: "Падарочные наборы",
          img: require("../Header-catalog-btn/images/Category-list/gift-sets.webp"),
          menu: false,
        },
      ],
    },
    {
      id: 11,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/scooter.jpg"),
      name: "Развлечение и хобби",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/sony.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/apple.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Книги",
          img: require("../Header-catalog-btn/images/Category-list/books.webp"),
          menu: [
            "Художественная литература",
            "Нехудожественная литература",
            "Психология и саморазвитие",
            "Бизнес и финансы",
          ],
        },
        {
          id: 2,
          name: "Квадракоптеры",
          img: require("../Header-catalog-btn/images/Category-list/quadcopters.webp"),
          menu: false,
        },
        {
          id: 3,
          name: "Акссесуары для квадракоптеров",
          img: require("../Header-catalog-btn/images/Category-list/accessories-for-quadcopters.webp"),
          menu: false,
        },
        {
          id: 5,
          name: "Оформление праздников",
          img: require("../Header-catalog-btn/images/Category-list/holiday-decoration.webp"),
          menu: ["Акссесуары для праздников"],
        },
      ],
    },
    {
      id: 12,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/armchair.webp"),
      name: "Дом, мебель, ремонт",
      brand: [
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/bureaucrat.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/metta.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/chairman.webp"),
        require("../../store/Header-catalog-btn/images/Category-list/brand-icons/samurai.webp"),
      ],
      lists: [
        {
          id: 1,
          name: "Посуда",
          img: require("../Header-catalog-btn/images/Category-list/dishes.webp"),
          menu: [
            "Кастрюли",
            "Сковороды",
            "Сотейники",
            "Все для чая",
            "Крышки",
            "Хранение продуктов",
            "Сервизы и наборы",
            "Кухонные аксессуары",
            "Ножи",
            "Кружки, стаканы и бокалы",
            "Формы для духовки",
            "Туристическая посуда",
            "Мельницы и емкости для специй",
            "Ковши",
            "Бутылки для напитков",
          ],
        },
        {
          id: 2,
          name: "Уход за одеждой и бельем",
          img: require("../Header-catalog-btn/images/Category-list/care-of-clothes-and-linen.webp"),
          menu: [
            "Гладильные доски",
            "Машинки для снятия катышков",
            "Сушилки для белья",
            "Чехлы для гладильных досок",
          ],
        },
        {
          id: 3,
          name: "Кресла",
          img: require("../Header-catalog-btn/images/Category-list/armchairs.webp"),
          menu: ["Игровые", "Офисные", "Для руководителей"],
        },
        {
          id: 4,
          name: "Умный дом",
          img: require("../Header-catalog-btn/images/Category-list/smart-home.webp"),
          menu: [
            "Датчики",
            "Розетки и фильтра",
            "Лампы и лампочки",
            "Пульты ДУ",
          ],
        },
        {
          id: 5,
          name: "Инструменты",
          img: require("../Header-catalog-btn/images/Category-list/tools.webp"),
          menu: [
            "Электроинструменты",
            "Наборы инструментов и оснастки",
            "Расходные материалы и оснастка для инструмента",
          ],
        },
        {
          id: 6,
          name: "Освещение",
          img: require("../Header-catalog-btn/images/Category-list/lighting.webp"),
          menu: ["Лампы", "Светильники", "Фонари"],
        },
        {
          id: 7,
          name: "Фурнитуры для мебели",
          img: require("../Header-catalog-btn/images/Category-list/furniture-fittings.webp"),
          menu: false,
        },
        {
          id: 8,
          name: "Товары для отдыха",
          img: require("../Header-catalog-btn/images/Category-list/leisure-goods.webp"),
          menu: ["Грили", "Аксессуары для грилей и мангалов"],
        },
        {
          id: 9,
          name: "Сумки",
          img: require("../Header-catalog-btn/images/Category-list/bags.jpg"),
          menu: false,
        },
        {
          id: 9,
          name: "Звонки",
          img: require("../Header-catalog-btn/images/Category-list/calls.webp"),
          menu: false,
        },
        {
          id: 10,
          name: "Спорт и одежда",
          img: require("../Header-catalog-btn/images/Category-list/sports-and-clothing.webp"),
          menu: [
            "Фитнес и акссесуары",
            "Силовые тренировки",
            "Мячи",
          ],
        },
      ],
    },
    {
      id: 13,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/DVR.webp"),
      name: "Автомобильная техника",
      brand: false,
      lists: [
        {
          id: 1,
          name: "Электроника и техника",
          img: require("../Header-catalog-btn/images/Category-list/electronics-and-technology.webp"),
          menu: [
            "Видеорегистраторы",
          ],
        },
        {
          id: 2,
          name: "Аудио и видео",
          img: require("../Header-catalog-btn/images/Category-list/audio-and-video.webp"),
          menu: [
            "FM-модуляторы",
          ],
        },
        {
          id: 3,
          name: "Аксессуары для автомобилей",
          img: require("../Header-catalog-btn/images/Category-list/car-accessories.webp"),
          menu: [
            "Кресла детские автомобильные",
            "Провода, кабели, адаптеры",
            "Прочие аксессуары",
            "Автомобильные зарядные устройства",
            "Автомобильные держатели",
          ],
        },
      ]
    },
    {
      id: 14,
      img: require("../../components/Header/images/nav-images/main-menu/catalog-list/discounted.webp"),
      name: "Уценённые товары",
      brand: false,
      lists: [
        {
          id: 1,
          name: "Компьютерная техника и периферия",
          img: require("../Header-catalog-btn/images/Category-list/computer-equipment-and-peripherals.webp"),
          menu: [
            "Комплектующие",
            "Ноутбуки УЦ",
            "Моноблоки УЦ",
            "Периферийные устройства",
            "Кресла УЦ",
            "Устройства хранения данных УЦ",
            "Кабели и аксессуары УЦ",
          ],
        },
        {
          id: 2,
          name: "Бытовая техника",
          img: require("../Header-catalog-btn/images/Category-list/household-appliances.webp"),
          menu: [
            "Крупная бытовая техника",
            "Техника для дома",
            "Техника для кухни",
          ],
        },
        {
          id: 3,
          name: "Телефоны и гаджеты",
          img: require("../Header-catalog-btn/images/Category-list/phones-and-gadgets.webp"),
          menu: [
            "Сотовые телефоны УЦ",
            "Планшеты УЦ",
            "Смарт-часы и фитнес-браслеты УЦ",
            "Наушники УЦ",
            "Фотоаппараты УЦ",
            "Аксессуары УЦ",
          ],
        },
        {
          id: 4,
          name: "Климатическая техника",
          img: require("../Header-catalog-btn/images/Category-list/climate-technology.webp"),
          menu: [
            "Кондиционеры УЦ",
            "Вентиляторы УЦ",
            "Обогреватели УЦ",
            "Увлажнители и очистители воздуха УЦ",
          ],
        },
        {
          id: 5,
          name: "Телевизоры, аудио, видео",
          img: require("../Header-catalog-btn/images/Category-list/TVs-audio-video.webp"),
          menu: [
            "Телевизоры УЦ",
            "Аксессуары для ТВ УЦ",
          ],
        },
        {
          id: 6,
          name: "Офисная техника и сетио",
          img: require("../Header-catalog-btn/images/Category-list/office-equipment-and-networks.webp"),
          menu: [
            "Принтеры и МФУ УЦ",
            "Сети УЦ",
            "Камеры видеонаблюдения УЦ",
          ],
        },
        {
          id: 7,
          name: "Красота и здоровье",
          img: require("../Header-catalog-btn/images/Category-list/beauty-and-health.webp"),
          menu: [
            "Фены УЦ",
            "Приборы для укладки УЦ",
            "Машинки для стрижки УЦ",
            "Мужские электробритвы УЦ",
            "Эпиляторы УЦ",
            "Массажеры УЦ",
            "Тонометры УЦ",
          ],
        },
        {
          id: 8,
          name: "Игры, развлечения, хобби",
          img: require("../Header-catalog-btn/images/Category-list/games-entertainment-hobbies.jpg"),
          menu: [
            "Электротранспорт УЦ",
            "Книги УЦ",
          ],
        },
        {
          id: 9,
          name: "Автотехника",
          img: require("../Header-catalog-btn/images/Category-list/automotive-equipment.webp"),
          menu: [
            "Кресла автомобильные",
          ],
        },
        {
          id: 10,
          name: "Аксессуары",
          img: require("../Header-catalog-btn/images/Category-list/accessories-for-pc.webp"),
          menu: false,
        },
      ]
    },
  ],
};

export const reducerCatalogList = (state = defaultState, action) => {
  switch (action.type) {
    case "CATALOG":
      return { ...state, catalogList: [state.catalogList]};
    default:
      return state;
  }
};
